# Site settings
url: "https://walkercraig.github.io/chicagojournal"
baseurl: '/chicagojournal'
production_url: 'https://walkercraig.github.io/chicagojournal'
name: 'Chicago Journal'
description: 
meta_description: 
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'chicagostaricon.png'
  greetings: "Notes on the Great American City"
favicon: '/favicon.ico'
disqus: 
mailchimp_url: '//walkercraig.us11.list-manage.com/subscribe/post?u=b845f7d1807ad41b6c0437990&amp;id=7bd2f97cd8'
# Add your GA Tracking Id
ga_analytics: G-7Z1MEJ4574

# Contact form settings
email: editor@chicagojournal.com  
contact_page_description: "Feel free to contact us with any questions, concerns, or work related inquiries. You may also reach us by sending an email direct to the following address: editor at chicagojournal dot com."
thankyou_page_description: "Your message has been successfully sent. We will contact you soon!"

# Social links
twitter: 'chicagojournal'
facebook: 'chicagojournal'
instagram: 'chicago.journal'

# Navigation
navigation:
  - text: Home
    url: /chicagojournal
  - text: About
    url: /chicagojournal/about
  - text: Commentary
    url: /chicagojournal/tags/index.html#comment
  - text: Features
    url: /chicagojournal/tags/index.html#features
  - text: Contact
    url: /chicagojournal/contact
  - text: Shop
    url: https://www.bonfire.com/store/chicagojournal/
  - text: Donate
    url: /donate
  - text: Search
    url: /search

# Required Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown
kramdown:
  input: GFM          # lets you keep GitHub-style tables & fences
  footnote_nr: 1      # optional – first number in the series

# Sass
sass:
  sass_dir: _sass
  style: compressed

remote_theme: royce
